title: Scratch 3.0 Phrasebook
hero_image: images/banner.png
description: Learn useful phrases in a variety of languages in this fun and interactive phrasebook
version: 4
listed: false
copyedit: false
ingredient: false
last_tested: "2018-12-03"
steps:
  - title: Introduction
  - title: Scratch 3.0 new look
  - title: Drawing sprites
  - title: Google translate
  - title: Text to speech
  - title: More phrases
  - title: More languages
  - title: "Challenge: something"
    challenge: true
